# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6, unique=True, verbose_name='Sigla do Motivo do Afastamento')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Afastamento')),
            ],
            options={
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
                ('data_inicio', models.DateField(verbose_name='Data do início do Exercício')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data do fim do exercício')),
                ('afastamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senadores.Afastamento')),
            ],
            options={
                'ordering': ('mandato', 'data_inicio'),
            },
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de início da Legislatura')),
                ('data_fim', models.DateField(verbose_name='Data de fim da Legislatura')),
            ],
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mandato', models.CharField(max_length=6, verbose_name='Código do Mandato')),
                ('uf', models.CharField(max_length=2, verbose_name='UF do Estado ao qual o mandato é vinculado')),
                ('participacao', models.CharField(max_length=20, verbose_name='O tipo de participação')),
                ('primeira_legislatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeira', to='senadores.Legislatura')),
                ('segunda_legislatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segunda', to='senadores.Legislatura')),
            ],
        ),
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_parlamentar', models.CharField(max_length=10, verbose_name='Código do Parlamentar')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome Político')),
                ('nome_completo', models.CharField(max_length=45, verbose_name='Nome Completo do Parlamentar')),
                ('uf', models.CharField(max_length=2, verbose_name='UF do Estado que foi eleito')),
                ('forma_tratamento', models.CharField(max_length=15, verbose_name='Forma de Tratamento')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('foto_url', models.URLField(verbose_name='URL para foto do Parlamentar')),
                ('pagina_url', models.URLField(verbose_name='Endereço da Página do Parlamentar')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Partido')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
            ],
            options={
                'ordering': ('sigla',),
            },
        ),
        migrations.AddField(
            model_name='parlamentar',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senadores.Partido'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='mandato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senadores.Mandato'),
        ),
    ]
