# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senadores', '0002_auto_20170427_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislatura',
            name='codigo',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='Código da Legislatura'),
            preserve_default=False,
        ),
    ]
