# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senadores', '0003_legislatura_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='parlamentar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='senadores.Parlamentar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='afastamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senadores.Afastamento'),
        ),
    ]
