# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senadores', '0004_auto_20170427_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoSuplentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição da participação')),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senadores.Mandato')),
                ('suplente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senadores.Parlamentar')),
            ],
            options={
                'ordering': ('mandato', 'suplente'),
            },
        ),
    ]
