# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senadores', '0005_mandatosuplentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
