# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senadores', '0006_auto_20170427_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='nome',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome Político'),
        ),
    ]
